teamcity-kubernetes-plugin-server/src/main/java/jetbrains/buildServer/helm/HelmConstantsBean.java
package jetbrains.buildServer.helm;

/**
 * Created by Evgeniy Koshkin (evgeniy.koshkin@jetbrains.com) on 17.10.17.
 */
public class HelmConstantsBean {
    public String getChartKey() {
        return HelmConstants.CHART;
    }

    public String getReleaseName() {
        return HelmConstants.RELEASE_NAME;
    }

    public String getRevision() {
        return HelmConstants.REVISION;
    }

    public String getAdditionalFlagsKey() {
        return HelmConstants.ADDITIONAL_FLAGS;
    }

    public String getDeleteCommandId() {
        return HelmConstants.HELM_DELETE_COMMAND_NAME;
    }

    public String getInstallCommandId() {
        return HelmConstants.HELM_INSTALL_COMMAND_NAME;
    }

    public String getRollbackCommandId() {
        return HelmConstants.HELM_ROLLBACK_COMMAND_NAME;
    }

    public String getTestCommandId() {
        return HelmConstants.HELM_TEST_COMMAND_NAME;
    }

    public String getUpgradeCommandId() {
        return HelmConstants.HELM_UPGRADE_COMMAND_NAME;
    }
}

teamcity-kubernetes-plugin-server/src/main/java/jetbrains/buildServer/helm/HelmParametersBean.java
package jetbrains.buildServer.helm;

import java.util.Collection;

/**
 * Created by Evgeniy Koshkin (evgeniy.koshkin@jetbrains.com) on 28.11.17.
 */
public class HelmParametersBean {
    public String getCommandKey() {
        return HelmConstants.COMMAND_ID;
    }

    public Collection<HelmCommand> getCommands() {
        return HelmCommands.getAll();
    }
}

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/editDelete.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="l" tagdir="/WEB-INF/tags/layout" %>
<%@ taglib prefix="admin" tagdir="/WEB-INF/tags/admin" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<tr>
    <th><label for="${constants.deleteCommandId}${constants.releaseName}">Release name: <l:star/></label></th>
    <td>
        <span>
            <props:textProperty name="${constants.deleteCommandId}${constants.releaseName}" className="longField"/>
        </span>
        <span class="error" id="error_${constants.deleteCommandId}${constants.releaseName}"></span>
        <span class="smallNote">Release name to delete from Kubernetes. Removes all of the resources associated with the last release of the chart.</span>
    </td>
</tr>

<tr class="advancedSetting">
    <th><label for="${constants.deleteCommandId}${constants.additionalFlagsKey}">Additional 'helm delete' command flags: </label></th>
    <td><props:textProperty name="${constants.deleteCommandId}${constants.additionalFlagsKey}" className="longField"/>
        <span class="error" id="error_${constants.deleteCommandId}${constants.additionalFlagsKey}"></span>
        <span class="smallNote">Additional options for 'helm delete' command line</span>
    </td>
</tr>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/editHelm.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="l" tagdir="/WEB-INF/tags/layout" %>
<%@ taglib prefix="admin" tagdir="/WEB-INF/tags/admin" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="teamcityPluginResourcesPath" scope="request" type="java.lang.String"/>
<jsp:useBean id="helmParametersBean" class="jetbrains.buildServer.helm.HelmParametersBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<c:set var="commandTitle">Command:<bs:help urlPrefix="https://docs.helm.sh/helm/#helm" file=""/></c:set>
<props:selectSectionProperty name="${helmParametersBean.commandKey}" title="${commandTitle}" note="">
    <props:selectSectionPropertyContent value="" caption="-- Choose Helm command --"/>
    <c:forEach items="${helmParametersBean.commands}" var="command">
        <props:selectSectionPropertyContent value="${command.id}" caption="${command.displayName}">
            <jsp:include page="${teamcityPluginResourcesPath}/helm/${command.editParamsJspFile}"/>
        </props:selectSectionPropertyContent>
    </c:forEach>
</props:selectSectionProperty>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/editInstall.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="l" tagdir="/WEB-INF/tags/layout" %>
<%@ taglib prefix="admin" tagdir="/WEB-INF/tags/admin" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<tr>
    <th><label for="${constants.chartKey}">Helm chart: <l:star/></label></th>
    <td>
      <span>
        <props:textProperty name="${constants.installCommandId}${constants.chartKey}" className="longField"/>
        <bs:vcsTree fieldId="${constants.installCommandId}${constants.chartKey}" treeId="${constants.installCommandId}${constants.chartKey}"/>
      </span>
        <span class="smallNote">Chart to install. Can be a chart reference, path to packaged chart or unpacked chart directory, or absolute URL</span>
        <span class="error" id="error_${constants.installCommandId}${constants.chartKey}"></span>
    </td>
</tr>

<tr class="advancedSetting">
    <th><label for="${constants.installCommandId}${constants.additionalFlagsKey}">Additional 'helm install' command flags: </label></th>
    <td><props:textProperty name="${constants.installCommandId}${constants.additionalFlagsKey}" className="longField"/>
        <span class="error" id="error_${constants.installCommandId}${constants.additionalFlagsKey}"></span>
        <span class="smallNote">Additional options for 'helm install' command line</span>
    </td>
</tr>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/editRollback.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="l" tagdir="/WEB-INF/tags/layout" %>
<%@ taglib prefix="admin" tagdir="/WEB-INF/tags/admin" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<tr>
    <th><label for="${constants.rollbackCommandId}${constants.releaseName}">Release name: <l:star/></label></th>
    <td>
        <span>
            <props:textProperty name="${constants.rollbackCommandId}${constants.releaseName}" className="longField"/>
        </span>
        <span class="error" id="error_${constants.rollbackCommandId}${constants.releaseName}"></span>
        <span class="smallNote">Release to rolls back.</span>
    </td>
</tr>

<tr>
    <th><label for="${constants.rollbackCommandId}${constants.revision}">Revision: <l:star/></label></th>
    <td>
      <span>
        <props:textProperty name="${constants.rollbackCommandId}${constants.revision}" className="longField"/>
      </span>
        <span class="smallNote">Previous release revision.</span>
        <span class="error" id="error_${constants.rollbackCommandId}${constants.revision}"></span>
    </td>
</tr>

<tr class="advancedSetting">
    <th><label for="${constants.rollbackCommandId}${constants.additionalFlagsKey}">Additional 'helm rollback' command flags: </label></th>
    <td><props:textProperty name="${constants.rollbackCommandId}${constants.additionalFlagsKey}" className="longField"/>
        <span class="error" id="error_${constants.rollbackCommandId}${constants.additionalFlagsKey}"></span>
        <span class="smallNote">Additional options for 'helm rollback' command line</span>
    </td>
</tr>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/editTest.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="l" tagdir="/WEB-INF/tags/layout" %>
<%@ taglib prefix="admin" tagdir="/WEB-INF/tags/admin" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<tr>
    <th><label for="${constants.testCommandId}${constants.releaseName}">Release name: <l:star/></label></th>
    <td>
        <span>
            <props:textProperty name="${constants.testCommandId}${constants.releaseName}" className="longField"/>
        </span>
        <span class="error" id="error_${constants.testCommandId}${constants.releaseName}"></span>
        <span class="smallNote">Release name to test. The tests to be run are defined in the chart that was installed.</span>
    </td>
</tr>

<tr class="advancedSetting">
    <th><label for="${constants.testCommandId}${constants.additionalFlagsKey}">Additional 'helm test' command flags: </label></th>
    <td><props:textProperty name="${constants.testCommandId}${constants.additionalFlagsKey}" className="longField"/>
        <span class="error" id="error_${constants.testCommandId}${constants.additionalFlagsKey}"></span>
        <span class="smallNote">Additional options for 'helm test' command line</span>
    </td>
</tr>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/editUpgrade.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="l" tagdir="/WEB-INF/tags/layout" %>
<%@ taglib prefix="admin" tagdir="/WEB-INF/tags/admin" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<tr>
    <th><label for="${constants.upgradeCommandId}${constants.releaseName}">Release name: <l:star/></label></th>
    <td>
        <span>
            <props:textProperty name="${constants.upgradeCommandId}${constants.releaseName}" className="longField"/>
        </span>
        <span class="error" id="error_${constants.upgradeCommandId}${constants.releaseName}"></span>
        <span class="smallNote">Release to upgrade.</span>
    </td>
</tr>

<tr>
    <th><label for="${constants.upgradeCommandId}${constants.chartKey}">Chart: <l:star/></label></th>
    <td>
      <span>
        <props:textProperty name="${constants.upgradeCommandId}${constants.chartKey}" className="longField"/>
        <bs:vcsTree fieldId="${constants.upgradeCommandId}${constants.chartKey}" treeId="${constants.upgradeCommandId}${constants.chartKey}"/>
      </span>
        <span class="smallNote">New version of chart.</span>
        <span class="error" id="error_${constants.upgradeCommandId}${constants.chartKey}"></span>
    </td>
</tr>

<tr class="advancedSetting">
    <th><label for="${constants.upgradeCommandId}${constants.additionalFlagsKey}">Additional 'helm upgrade' command flags: </label></th>
    <td><props:textProperty name="${constants.upgradeCommandId}${constants.additionalFlagsKey}" className="longField"/>
        <span class="error" id="error_${constants.upgradeCommandId}${constants.additionalFlagsKey}"></span>
        <span class="smallNote">Additional options for 'helm upgrade' command line</span>
    </td>
</tr>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/viewDelete.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<div class="parameter">
    Release: <strong><props:displayValue name="${constants.deleteCommandId}${constants.releaseName}" emptyValue="not specified"/></strong>
</div>

<div class="parameter">
    Additional command flags: <strong><props:displayValue name="${constants.deleteCommandId}${constants.additionalFlagsKey}" emptyValue="not specified"/></strong>
</div>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/viewHelm.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="teamcityPluginResourcesPath" scope="request" type="java.lang.String"/>
<jsp:useBean id="helmParametersBean" class="jetbrains.buildServer.helm.HelmParametersBean"/>

<c:forEach items="${helmParametersBean.commands}" var="command">
    <c:if test="${propertiesBean.properties[helmParametersBean.commandKey] eq command.id}">
        <div class="parameter">
            Command: <strong><c:out value="${command.displayName}"/></strong>
        </div>
        <jsp:include page="${teamcityPluginResourcesPath}/helm/${command.viewParamsJspFile}"/>
    </c:if>
</c:forEach>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/viewInstall.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<div class="parameter">
    Chart: <strong><props:displayValue name="${constants.installCommandId}${constants.chartKey}" emptyValue="not specified"/></strong>
</div>

<div class="parameter">
    Additional command flags: <strong><props:displayValue name="${constants.installCommandId}${constants.additionalFlagsKey}" emptyValue="not specified"/></strong>
</div>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/viewRollback.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<div class="parameter">
    Release: <strong><props:displayValue name="${constants.rollbackCommandId}${constants.releaseName}" emptyValue="not specified"/></strong>
</div>

<div class="parameter">
    Revision: <strong><props:displayValue name="${constants.rollbackCommandId}${constants.revision}" emptyValue="not specified"/></strong>
</div>

<div class="parameter">
    Additional command flags: <strong><props:displayValue name="${constants.rollbackCommandId}${constants.additionalFlagsKey}" emptyValue="not specified"/></strong>
</div>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/viewTest.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<div class="parameter">
    Release: <strong><props:displayValue name="${constants.testCommandId}${constants.releaseName}" emptyValue="not specified"/></strong>
</div>

<div class="parameter">
    Additional command flags: <strong><props:displayValue name="${constants.testCommandId}${constants.additionalFlagsKey}" emptyValue="not specified"/></strong>
</div>

teamcity-kubernetes-plugin-server/src/main/resources/buildServerResources/helm/viewUpgrade.jsp
<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="jetbrains.buildServer.helm.HelmConstantsBean"/>

<div class="parameter">
    Release: <strong><props:displayValue name="${constants.upgradeCommandId}${constants.releaseName}" emptyValue="not specified"/></strong>
</div>

<div class="parameter">
    Chart: <strong><props:displayValue name="${constants.upgradeCommandId}${constants.chartKey}" emptyValue="not specified"/></strong>
</div>

<div class="parameter">
    Additional command flags: <strong><props:displayValue name="${constants.upgradeCommandId}${constants.additionalFlagsKey}" emptyValue="not specified"/></strong>
</div>